import {v4 as uuidv4, v4} from "uuid";
import {IllegalArgumentError} from "../error/IllegalArgumentError";
import type {Group} from "./Group";
import {
    type ExtendedParamType,
    ExtendedToken,
    type ExtendedTokenMap,
    type ExtendedTokenType,
    type Token_depr
} from "./Token";
import {JSON_IDENTIFIERS} from "@src/common/utils/Constants.ts";


/**
 * The base class for all design system tokens.
 * @remarks
 * Direct instantiation of TokenNode is prohibited.
 * Use {@link ValueNode}, {@link GroupNode}, or {@link ReferenceNode}
 * to create the design system tokens.
 */
export abstract class TokenNode {
    id: string
    name: string
    abstract __identifier: string // Identifier used by discriminator for serialization/deserialization

    protected constructor(name: string, id: string) {
        this.id = id
        this.name = name
    }
}


/**
 * A token node representing a concrete Token (Token with a value).
 */
export class ValueNode<K extends keyof typeof ExtendedToken> extends TokenNode {
    value: any // TODO: Update to use a typesafe mapping
    __identifier = JSON_IDENTIFIERS.VALUE_NODE

    /**
     * Instantiate a Concrete TokenNode (ValueNode).
     *
     * @param name  The name of the ValueNode.
     * @param value The absolute value of the node, like "#fff".
     * @param id    The unique identifier of the GroupNode. Generated by default.
     */
    constructor(name: string, value: any, id: string = v4()) {
        super(name, id)
        this.value = value
    }
}


// new ValueNode<>
/**
 * A token node representing Group/Folder.
 */
export class GroupNode extends TokenNode {
    expanded: boolean
    children: TokenNode[]
    #childrenCache: Set<TokenNode>
    __identifier = JSON_IDENTIFIERS.GROUP_NODE

    /**
     * Instantiate a GroupNode.
     *
     * @param name     The name of the GroupNode.
     * @param children The list of child {@link TokenNode}s a Group encloses. Default: [].
     * @param expanded The flag that indicates whether a Group is expanded or collapsed. Default: false.
     * @param id       The unique identifier of the GroupNode. Generated by default.
     */
    constructor(name: string, children: TokenNode[] = [], expanded: boolean = false, id: string = v4()) {
        super(name, id)
        this.expanded = expanded
        this.#childrenCache = new Set()
        this.children = []
        children.forEach((child) => {
            // Only add the child if it has not been previously added
            if (!this.#childrenCache.has(child)) {
                this.#childrenCache.add(child)
                this.children.push(child)
            }
        })

    }

    /**
     * Convert the current instance of {@link GroupNode} into a JSON string.
     *
     * @returns A JSON string representation of the current instance.
     */
    toJson(): string {
        return JSON.stringify({
            name: this.name,
            id: this.id,
            expanded: this.expanded,
            children: this.children,
            __identifier: this.__identifier
        })
    }


    /**
     * Add a {@see TokenNode} as the current group's child.
     * @param node The {@see TokenNode} to add.
     */
    addChild(node: TokenNode) {
        if (!this.#childrenCache.has(node)) {
            this.children.push(node)
            this.#childrenCache.add(node)
        }
    }

    /**
     * Remove a child node from the current group if it exists.
     * @returns The removed node if it exists or null.
     */
    removeChild(node: TokenNode): TokenNode | null {
        // Store initial size so it can be later compared to check if a node has been removed
        const initialSize = this.children.length
        this.children = this.children.filter(child => child !== node)
        this.#childrenCache.delete(node)
        // If initialSize and current length of children is the same
        // then it means no element has been removed, so a null is returned
        return initialSize === this.children.length ? null : node
    }

}

/**
 * A token node representing a reference/alias.
 * @remarks
 * The token itself holds no value, and acts as a reference to another {@link TokenNode}.
 */
export class ReferenceNode extends TokenNode {
    reference: string;
    __identifier: string = JSON_IDENTIFIERS.REFERENCE_NODE;

    /**
     * Instantiate a {@link ReferenceNode}.
     * @param name      The name of the reference node.
     * @param reference The unique identifier of the node that this node is referencing.
     * @param id        The unique identifier of the ReferenceNode. Generated by default.
     */
    constructor(name: string, reference: string, id: string = v4()) {
        super(name, id);
        this.reference = reference
    }

}

//////////////////////DEPRECATED////////////////////

/**
 * The basic token node of the Design System tree.
 */
type BasicNode = {
    name: string;
    uid: string;
};


/**
 * A token node representing Group/Folder.
 */
// type GroupNode<K extends keyof typeof ExtendedToken> = {
//     entityType: "group";
//     expanded: boolean;
//     children: TokenNode<K>[];
// } & BasicNode;

/**
 * A token node representing a concrete Token (Token with a value).
 */
// type ValueNode<K extends keyof typeof ExtendedToken> = {
//     entityType: "token";
//     type: K;
//     valueByMode: Record<string, any>; // TODO: Add type safety
// } & BasicNode;

/**
 * A token node representing a reference/alias.
 * @remarks
 * The token itself holds no value, and acts as a reference to another
 * {@link ValueNode} or {@link ReferenceNode}.
 */
// type ReferenceNode<K extends keyof typeof ExtendedToken> = {
//     entityType: "reference";
//     referenceId: string;
//     type: K;
//     value: unknown;
// } & BasicNode;

/**
 * Unified TokenNode type.
 */
// export type TokenNode<K extends keyof typeof ExtendedToken> =
//     | GroupNode<K>
//     | ValueNode<K>
//     | ReferenceNode<K>;

/**
 * Construct a {@link ValueToken}.
 *
 * @param name        The human-readable name of the node.
 * @param valueByMode The key value pair of values that token holds. E.g: {dark: "#ffffff"}
 * @param type        The type of token.
 *                    Although explicit constraints are not applied, using a type (string value)
 *                    other than ones provided in {@link ExtendedTokenMap} is not recommended.
 * @param uid         The unique identifier of the node.
 *
 * @returns A {@link ValueToken} created with the passed-in paramters.
 */
// export function createValueNode<K extends keyof typeof ExtendedToken>(
//     name: string,
//     valueByMode: Record<string, any>,
//     type: K,
//     uid?: string | undefined,
// ): ValueNode<K> {
//     return {
//         name,
//         uid: uid || uuidv4(),
//         valueByMode: valueByMode,
//         entityType: "token",
//         type: type,
//     } as ValueNode<K>;
// }

/**
 * Construct a {@link GroupNode}.
 *
 * @param name     The human-readable name of the node.
 * @param expanded The state of the GroupNode, whether it's expanded or not.
 * @param uid      The unique identifier of the node.
 * @param children The child nodes of the current group.
 *
 * @returns A {@link GroupNode} created with the passed-in paramters.
 */
// export function createGroupNode<K extends keyof typeof ExtendedToken>(
//     name: string,
//     expanded: boolean = false,
//     children?: TokenNode<K>[],
//     uid?: string | undefined
// ): GroupNode<K> {
//     return {
//         name,
//         expanded,
//         uid: uid || v4(),
//         entityType: "group",
//         children: children || []
//     } as GroupNode<K>;
// }

// TODO: Update to Class
/**
 * Construct a {@link ReferenceNode}.
 *
 * @param name        The human-readable name of the node.
 * @param referenceId The unique identifier of the {@link ReferenceNode}, {@link ValueNode}, or
 *                    {@link GroupNode} that this node is aliasing.
 * @param uid         The unique identifier of the node.
 *
 * @returns A {@link ReferenceNode} created with the passed-in parameters.
 */
export function createReferenceNode<K extends keyof typeof ExtendedToken>(
    name: string,
    referenceId: string,
    uid?: string | undefined,
): ReferenceNode<K> {
    return {
        name,
        uid: uid || v4(),
        referenceId,
        entityType: "reference",
    } as ReferenceNode<K>;
}


/**
 * Add a {@link TokenNode} to a group.
 *
 * @param group The group to add the token to.
 * @param value The token to add.
 */
export function addToGroup<K extends keyof typeof ExtendedToken>(group: GroupNode<K>, value: TokenNode<K>) {
    // Only adds the token if it doesn't already exist in the group.
    if (getIndex(group, value) === -1)
        group.children = [...group.children, value]
}


/**
 * Remove a {@link TokenNode} from a group.
 *
 * @param group The group to remove the token from.
 * @param value The token to remove.
 *
 * @returns The removed {@link TokenNode} or null if it does not exist.
 */
export function removeFromGroup<K extends keyof typeof ExtendedToken>(group: GroupNode<K>, value: TokenNode<K>): TokenNode<K> | null {
    // Store the initial size of the group to ensure that the token exists
    const initialSize = group.children.length
    group.children = group.children.filter(node => node != value)

    // If the number of children(length) remains the same then, it means the `value` does not exist
    // and hence we return a null to indicate nothing was removed.
    return group.children.length === initialSize ? null : value
}

/**
 * Return the index of a given {@link TokenNode} in a group.
 *
 * @param group The group to search in.
 * @param value The token to search.
 *
 * @returns The index of the token if it exists, else -1.
 */
export function getIndex<K extends keyof typeof ExtendedToken>(group: GroupNode<K>, value: TokenNode<K>) {
    return group.children.findIndex(node => node == value)
}


/**
 * @deprecated Remove
 */
export type TokenNode_depr<K extends keyof typeof ExtendedToken> = {
    name: string;
    uid: string;
    value?: Group | Token_depr<K> | undefined;
    parentId?: string | undefined;
    reference?: string | undefined;
};

/**
 * Factory to create and initialize a {@link TokenNode_depr}.
 * @deprecated
 * @remarks
 * **Priority Logic:** If both `value` and `reference` are provided, `reference` takes
 * precedence and the resulting node's `value` will be set to `undefined`.
 *
 * @param name        The semantic identifier for the node.
 * @param value       The {@link Group} or {@link Token_depr} data. Optional if `reference` is provided.
 * @param uid         Manual UID override. If omitted, a v4 UUID is generated.
 * @param parentId    UID of the parent group.
 * @param reference   UID of the target node for aliasing.
 *
 * @returns A structured TokenNode.
 * @throws {@link IllegalArgumentError}
 * Thrown if both `value` and `reference` are undefined, as the node would have no data.
 */
export function createTokenNode<K extends keyof ExtendedTokenMap>(
    name: string,
    value: Group | Token_depr<K> | undefined,
    uid: string | undefined = undefined,
    parentId: string | undefined = undefined,
    reference: string | undefined = undefined,
): TokenNode_depr<K> {
    if (!value && !reference)
        throw new IllegalArgumentError(
            "Both value and reference cannot be undefined.",
        );

    return {
        name: name,
        uid: uid || uuidv4(),
        value: reference ? undefined : value,
        reference: reference,
        parentId: parentId,
    } as TokenNode_depr<K>;
}
