import { v4 as uuidv4 } from "uuid";
import { IllegalArgumentError } from "../error/IllegalArgumentError";
import type { Group } from "./Group";
import type { Token } from "./Token";

/**
 * Type encapsulating the atomic unit of Design System.
 * @note Although you can create Groups and Tokens, it is discouraged
 *
 * @export
 * @typedef {TokenNode}
 * @property {string} name - Name of the token
 * @property {string} uid - ID of then token
 * @property {?(Group|Token|undefined)} value - Value of the token. @see Group and @see Token for more details.
 *                                    Value is undefined only if this node is a reference to another node.
 * @property {?(string|undefined)} parentId - A reference to the enclosing group.
 *                               Can be kept undefined if this token is standalone.
 * @property {?(string|undefined)} reference - A reference to another token.
 *                                Used when referencing or parenting a node properties from another node.
 *                                Can be kept undefined if this token is the base token.
 *
 * @example
 * {
 *  name: "red-500",
 *  uid: "91940fc4-8e7a-43f5-96be-a9f363328590",
 *  value: { valueByMode: { default: "#770000" }, type: "color" },
 *  parentId: "305748a4-6ff4-4f77-b05d-e81397e694ad", // Reference to a primitive group
 *  reference: undefined // Primitive token
 * }
 * {
 *  name: "primary-800",
 *  uid: "20d5bb9b-7ef5-493d-9bac-477d9da4ed8b",
 *  value: undefined,
 *  parentId: "d9b18215-5337-4118-ab2f-a280748eab15", // Reference to a primitive group
 *  reference: "776c33ca-3fc8-435f-84b5-7a24dcf3c5f4" // Reference to a primitive token
 * }
 */
export type TokenNode = {
    name: string;
    uid: string;
    value?: Group | Token | undefined;
    parentId?: string | undefined;
    reference?: string | undefined;
};

/**
 * Generates a token node based on the provided values.
 *
 * @export
 * @param {string} name The name of the token node.
 * @param {?(Group | Token | undefined)} value The value of the token node.
 *                                       Either a @ref Token or @ref Group or undefined(ONLY IF @param reference is passed in).
 *                                       Can be undefined if the token has a reference.
 *                                       If passed in with both a value and a reference, then it's reference will take priority and `value` will be made undefined.
 * @param {?string} [uid=undefined] Identifier for the node.
 *                                  Not recommended to pass in while creating a new node as it gets autogenerated.
 * @param {?string} [parentId=undefined] Parent of the current node.
 *                                       If this node is the parent then can be undefined.
 * @param {?string} [reference=undefined] Then reference of the node to another node from another level.
 * @returns {TokenNode} The generated token node.
 *
 * @throws @ref IllegalArgumentError if both the value and reference are passed in as undefined.
 */
export function createTokenNode(
    name: string,
    value: Group | Token | undefined,
    uid: string | undefined = undefined,
    parentId: string | undefined = undefined,
    reference: string | undefined = undefined,
): TokenNode {
    if (!value && !reference)
        throw new IllegalArgumentError(
            "Both value and reference cannot be undefined.",
        );

    return {
        name: name,
        uid: uid || uuidv4(),
        value: reference ? undefined : value,
        reference: reference,
        parentId: parentId,
    } as TokenNode;
}
